### ISSUE TITLE
feat: use better paths for the solvers

### ISSUE THREAD

**Issue by jolars** [jolars/benchmark_lasso_path#9]
Many solvers for fitting the full path, such as glmnet, employ path-stopping criteria to stop the path prematurely if the model saturates before completion. This is, in my opinion, very reasonable behavior since otherwise we an run into weird degenerate solutions, but we've had to turn it off because otherwise the algorithms cannot be compared properly.

One way to fix this would be to precompute a reasonable path for each data set using a solver that employs these types of checks (such as glmnet or Lasso.jl) and store the path along with each data set, but I'm not sure if that would work with the current API.

**Comment by mathurinm** [comment]
I see two ways of doing this:
- hardcode it for every dataset and returning in in the `data` dict, while committing the script you used for transparency
-  compute it in `Objective.set_data`, which is more reproducible, but more costly.


Also, what do you mean by "degenerate" solution ?

**Comment by jolars** [comment]
> I see two ways of doing this:
> 
>     * hardcode it for every dataset and returning in in the `data` dict, while committing the script you used for transparency
> 
>     * compute it in `Objective.set_data`, which is more reproducible, but more costly.
> 
> 

Good points, which one would you prefer? I probably like 2 better.

> Also, what do you mean by "degenerate" solution ?

Yeah, I take that back. More like "unstable".

**Comment by mathurinm** [comment]
I'd do 1 while feeling guilty and write a TODO to implement 2
I fear 2 will take a lot of time at each run which is frustrating

**Comment by jolars** [comment]
> I'd do 1 while feeling guilty and write a TODO to implement 2 I fear 2 will take a lot of time at each run which is frustrating

haha, actually I think number 2 might just be the lazier one. I'm not sure it will take so much time actually. We're fitting the full path several times over anyway.
